language: php

sudo: false

matrix:
  include:
    - php: 5.5
      env: COLLECT_COVERAGE=true VALIDATE_CODING_STYLE=false
    - php: 5.6
      env: COLLECT_COVERAGE=true VALIDATE_CODING_STYLE=true
    - php: 7.0
      env: COLLECT_COVERAGE=true VALIDATE_CODING_STYLE=false
    - php: 7.1
      env: COLLECT_COVERAGE=true VALIDATE_CODING_STYLE=false
    - php: hhvm
      env: COLLECT_COVERAGE=false VALIDATE_CODING_STYLE=false
  allow_failures:
    - php: hhvm
  fast_finish: true

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - travis_retry composer self-update

install:
  - travis_retry composer update --no-interaction --prefer-source

script:
  - composer phpunit

after_script:
 - if [ "$COLLECT_COVERAGE" == "true" ]; then wget https://scrutinizer-ci.com/ocular.phar && php ocular.phar code-coverage:upload --format=php-clover build/clover.xml; fi
 - if [ "$VALIDATE_CODING_STYLE" == "true" ]; then composer phpcs fi
